### ISSUE TITLE
cannot start docker-compose

### ISSUE THREAD

**Issue by osallou** [dinuti/dinuti#37]
Starting docker-compose lead to errors
I updated compose to remove some "errors"

    diff --git a/docker-compose.yml b/docker-compose.yml
    index 2330a69..9c7ce89 100644
    --- a/docker-compose.yml
    +++ b/docker-compose.yml
    @@ -5,7 +5,7 @@ services:
         build: ./front
         volumes:
           - './front:/usr/src/app'
    -      - '/usr/src/app/node_modules/'
    +      # - '/usr/src/app/node_modules/'

=> local host node_modules should not be mounted in container (should not impact host system libraries/modules). All node modules etc... should be available in container
Volumes should be used only to backup container data
*front* should not be mounted too. All front web needed code should be put in container via Dockerfile and used within container. Local code should not be used (and built for prod)
This can be acceptable for dev/testing however.

         ports: 
           - '4200:4200'
         command: >
    @@ -16,8 +16,8 @@ services:
         build: ./back
         ports:
           - '3000:3000'
    -    links:
    -      - mongo-service
    +    # links:
    +    #   - mongo-service

=>links is not needed, compose creates a virtual network where containers can communitate with the their name, containers do not need to expose their ports

         depends_on:
           - mongo-service
         command: >
    @@ -27,5 +27,5 @@ services:
         image: mongo
         # volumes:
         #   - ./back/dinuti:/data/db/
    -    ports:
    -      - '27017:27017'
    \ No newline at end of file
    +    # ports:
    +    #   - '27017:27017'

=> mongo should not be exposed

    front-container  | Could not find module "@angular-devkit/build-angular" from "/usr/src/app".
    front-container  | Error: Could not find module "@angular-devkit/build-angular" from "/usr/src/app".
    front-container  |     at Object.resolve (/usr/local/lib/node_modules/@angular/cli/node_modules/@angular-devkit/core/node/resolve.js:141:11)
    front-container  |     at Observable.rxjs_1.Observable [as _subscribe] (/usr/local/lib/node_modules/@angular/cli/node_modules/@angular-devkit/architect/src/architect-legacy.js:153:40)
    front-container  |     at Observable._trySubscribe (/usr/local/lib/node_modules/@angular/cli/node_modules/rxjs/internal/Observable.js:44:25)
    front-container  |     at Observable.subscribe (/usr/local/lib/node_modules/@angular/cli/node_modules/rxjs/internal/Observable.js:30:22)
    front-container  |     at /usr/local/lib/node_modules/@angular/cli/node_modules/rxjs/internal/Observable.js:99:19
    front-container  |     at new Promise (<anonymous>)
    front-container  |     at Observable.toPromise (/usr/local/lib/node_modules/@angular/cli/node_modules/rxjs/internal/Observable.js:97:16)
    front-container  |     at ServeCommand.initialize (/usr/local/lib/node_modules/@angular/cli/models/architect-command.js:67:96)
    front-container  |     at process._tickCallback (internal/process/next_tick.js:68:7)
    front-container  |     at Function.Module.runMain (internal/modules/cjs/loader.js:757:11)
    front-container  |     at startup (internal/bootstrap/node.js:283:19)
    front-container  |     at bootstrapNodeJSCore (internal/bootstrap/node.js:622:3)
    back-container   | [nodemon] 1.19.0
    back-container   | [nodemon] to restart at any time, enter `rs`
    back-container   | [nodemon] watching: *.*
    back-container   | [nodemon] starting `ts-node ./app.ts mongodb://mongo-service:27017/dinuti`
    front-container exited with code 1
    back-container   | 
    back-container   | /usr/src/app/node_modules/ts-node/src/index.ts:307
    back-container   |         throw new TSError(formatDiagnostics(diagnosticList, cwd, ts, lineOffset))
    back-container   |               ^
    back-container   | TSError: ⨯ Unable to compile TypeScript
    back-container   | app.ts (36,54): Property 'port' does not exist on type 'string | AddressInfo'.
    back-container   |   Property 'port' does not exist on type 'string'. (2339)
    back-container   |     at getOutput (/usr/src/app/node_modules/ts-node/src/index.ts:307:15)
    back-container   |     at /usr/src/app/node_modules/ts-node/src/index.ts:336:16
    back-container   |     at Object.compile (/usr/src/app/node_modules/ts-node/src/index.ts:498:11)
    back-container   |     at Module.m._compile (/usr/src/app/node_modules/ts-node/src/index.ts:392:43)
    back-container   |     at Module._extensions..js (module.js:635:10)
    back-container   |     at Object.require.extensions.(anonymous function) [as .ts] (/usr/src/app/node_modules/ts-node/src/index.ts:395:12)
    back-container   |     at Module.load (module.js:545:32)
    back-container   |     at tryModuleLoad (module.js:508:12)
    back-container   |     at Function.Module._load (module.js:500:3)
    back-container   |     at Function.Module.runMain (module.js:665:10)
    back-container   | [nodemon] app crashed - waiting for file changes before starting...
    ^CGracefully stopping... (press Ctrl+C again to force)

Missing module seems an issue with built dockerfile not installing all required code.
back-container port issue seems to say that something is missing for port declaration

**Comment by osallou** [comment]
backend in compose should open port 4000 (else not reachable for socket.io)
